import Head from "next/head";

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>React Board & Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
    </>
  );
}
